### PR TITLE
Add Syntax Highlighting for SugarSS

### PR DESCRIPTION
**Pull request by maxinspace**
Totally based on Atom plugin.

Note for Reviewers:
1) About README: 
Should I simply add Link to SugarSS syntax to current PostCSS README?

### CODE REVIEW

**Comment by hudochenkov** [comment]
1. Yeah, just add something to current readme about SugarSS, so people would know that this syntax highlighting works with SugarSS.
2. Don't remove Syntaxes/PostCSS.tmLanguage.

Thank you for doing this!

**Comment by maxinspace** [comment]
@hudochenkov: updated Readme, feel free to check and merge 👍 

Thanks for sharing open-source offers on Cult Of Martians, haven't had a chance to do something for open-source community for a while :)

**Comment by ai** [comment]
I asked my friends to test syntax file from [Syntax-highlighting-for-SugarSS](https://github.com/maximlarionov/Syntax-highlighting-for-SugarSS) and they reported that it works very good.

**Comment by ai** [comment]
@hudochenkov please ping me when you release it. I will write a tweets :)

**Comment by hudochenkov** [comment]
Thank you, @maximlarionov!

@ai I've just released, but it's not updated in Package Control yet. It isn't available to users. I suppose it will be available in an hour.

**Pull request merged**
